# Generated by Django 5.2.8 on 2026-01-22 17:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RunRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField()),
                ("distance_km", models.FloatField()),
                ("duration_minutes", models.FloatField()),
                (
                    "strava_activity_id",
                    models.BigIntegerField(blank=True, null=True, unique=True),
                ),
                ("avg_heart_rate", models.IntegerField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
                ("weather", models.CharField(blank=True, max_length=100, null=True)),
                ("location", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "run_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("outdoor", "Outdoor"),
                            ("treadmill", "Treadmill"),
                            ("trail", "Trail"),
                            ("indoor_track", "Indoor Track"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("calories", models.IntegerField(blank=True, null=True)),
                ("temperature_c", models.FloatField(blank=True, null=True)),
                ("polyline", models.TextField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="runs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
