# Generated by Django 5.2.8 on 2025-11-14 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="RunRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField()),
                ("distance_km", models.FloatField()),
                ("duration_minutes", models.FloatField()),
                ("avg_heart_rate", models.IntegerField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
                ("weather", models.CharField(blank=True, max_length=100, null=True)),
                ("location", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "run_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("outdoor", "Outdoor"),
                            ("treadmill", "Treadmill"),
                            ("trail", "Trail"),
                            ("indoor_track", "Indoor Track"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("calories", models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
