# Generated by Django 5.2.8 on 2026-01-28 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("runs", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="runrecord",
            name="weather_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("updating", "Updating"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                ],
                default="pending",
                help_text="Weather data update status",
                max_length=20,
            ),
        ),
    ]
