# Generated by Django 5.2.8 on 2025-11-16 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("runs", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="runrecord",
            name="strava_activity_id",
            field=models.BigIntegerField(blank=True, null=True, unique=True),
        ),
    ]
