# Generated by Django 5.2.8 on 2025-11-18 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("runs", "0002_runrecord_strava_activity_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="runrecord",
            name="temperature_c",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
