# Generated by Django 5.2.8 on 2025-11-21 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("runs", "0003_runrecord_temperature_c"),
    ]

    operations = [
        migrations.AddField(
            model_name="runrecord",
            name="summary",
            field=models.TextField(blank=True, null=True),
        ),
    ]
