# Generated by Django 5.2.8 on 2025-11-21 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("runs", "0004_runrecord_summary"),
    ]

    operations = [
        migrations.RenameField(
            model_name="runrecord",
            old_name="summary",
            new_name="polyline",
        ),
    ]
